dataset: tinystories
run_name: tinystories_small

paths:
  checkpoint: checkpoints/tinystories_small/checkpoint.pt
  tokenizer: data/tinystories/tokenizer/model.pkl

model:
  vocab_size: 10000
  context_length: 128
  d_model: 256
  num_layers: 4
  num_heads: 4
  d_ff: null
  rope_theta: 10000.0

generation:
  prompt: "Once upon a time"
  max_tokens: 100
  temperature: 0.8
  top_k: null

device: cpu
