dataset: owt
run_name: owt

run_note: ""

vocab_size: 32000

paths:
  input_file: data/owt/tokenized/train.npy
  checkpoint_dir: checkpoints/owt/checkpoint.pt

load_checkpoint: 0
batch_size: 32
context_length: 128
d_model: 512
num_layers: 6
num_heads: 8
d_ff: null
rope_theta: 10000.0

train_steps: 5000
lr: 0.0005
max_lr: 0.0005
min_lr: 0.000005
warmup_iters: 200
b1: 0.9
b2: 0.99
weight_decay: 0.01
eps: 1.0e-8

device: cpu
